image: gcc:13.2
workflow:
  rules:
    - changes:
        - app/** 
        - lib/** 
        - tests/** 
        - CMakeLists.txt    
only:
  - main
stages:
  - build
  - test
build:
  stage: build
  before_script:
    - apt update && apt -y install cmake libgdal-dev
  script:
    - mkdir build
    - cd build
    - cmake -DFISHNET_APPS=OFF ..
    - cmake --build . -j 8
  artifacts:
    paths:
      - build/ # Preserving the build artifacts for the test stage
    expire_in: 1 hour
test:
  stage: test
  dependencies:
    - build
  before_script:
    - apt update && apt -y install cmake libgdal-dev
  script:
    - cd build
    - ctest --output-on-failure
