image: gcc:13.2

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake libgdal-dev
  script:
    - mkdir build
    - cd build
    - cmake -DFISHNET_APPS=OFF ..
    - cmake --build .
  artifacts:
    paths:
      - build/ # Preserving the build artifacts for the test stage
    expire_in: 1 hour

test:
  stage: test
  dependencies:
    - build
  before_script:
    - apt update && apt -y install cmake libgdal-dev
  script:
    - cd build
    - ls -la
    - file tests/graph/graphTest
    - ctest --output-on-failure
