services:
  memgraph:
    image: memgraph/memgraph
    container_name: memgraphDB
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE","--query-execution-timeout-sec=0"]
    volumes:
      - memgraph-logs:/var/log/memgraph
 
  fishnet-sda:
    image: logru/sda:latest
    depends_on:
      - memgraph
    container_name: sda-workflow
    volumes:
      - ${HOME}/.fishnet:/data
      - ${HOME}/.fishnet/working-directory:/tmp/fishnet
volumes:
  memgraph-logs:
    driver: local
  