services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE","--query-execution-timeout-sec=0"]
    volumes:
      - memgraph-logs:/var/log/memgraph
    networks:
      default: {}
 
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

  fishnet:
    image: fishnet:latest  # Replace with the actual fishnet image name
    container_name: fishnet
    depends_on:
      - memgraph
    networks:
      default: {}

volumes:
  memgraph-logs:
    driver: local

networks:
  default:
    name: fishnet-net
    attachable: true